export PS1="\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] "
export GL=/home/gl/projet_gl

PATH=$GL/src/main/bin:"$PATH"
PATH=$GL/src/test/script:"$PATH"
PATH=$GL/src/test/script/launchers:"$PATH"
PATH=/usr/local/ima/bin:"$PATH"

export JAVA_HOME=/usr/local/jdk-23.0.2+7
export PAH=$JAVA_HOME/bin:$PATH

export PATH
